# Generated by Django 4.0.4 on 2022-08-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='icon.jpg', upload_to='profile/'),
        ),
    ]
