# Generated by Django 4.0.4 on 2022-06-01 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctor_address_alter_doctor_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='address',
        ),
    ]
