# Generated by Django 4.0.4 on 2022-06-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_remove_doctor_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='username',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='contact_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
