# Generated by Django 4.0.4 on 2022-06-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_remove_doctor_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Prescription',
            field=models.ImageField(default='abc.png', upload_to='prescription'),
        ),
    ]
