# Generated by Django 4.0.4 on 2022-05-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointmentDate',
            new_name='appointment_date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patientId',
            new_name='patient_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctorName',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patientName',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists')], default='Cardiologist', max_length=40),
        ),
    ]
