# Generated by Django 4.0.4 on 2022-06-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_appointment_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='medical_report',
            field=models.ImageField(default='abc.png', upload_to='medical_reports'),
        ),
    ]
