# Generated by Django 4.0.4 on 2022-06-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_appointment_medical_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Checked', 'Checked')], default='Pending', max_length=10),
        ),
    ]
