# Generated by Django 4.0.4 on 2022-06-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_appointment_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='assign_to',
            field=models.IntegerField(default=0),
        ),
    ]
